# Generated by Django 2.0.2 on 2018-03-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='payroll_date',
            field=models.IntegerField(blank=True, default=29, null=True),
        ),
    ]
