# Generated by Django 2.0.2 on 2018-03-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='user_type',
        ),
    ]
