# Generated by Django 2.0.2 on 2018-03-05 12:50

from django.db import migrations, models
import django.db.models.deletion
import employers.models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_auto_20180302_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AddField(
            model_name='workdetail',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employers.JobTitle'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=employers.models.admin_avatar_location),
        ),
    ]
