# Generated by Django 2.0.2 on 2018-03-05 16:12

from django.db import migrations, models
import employers.models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_auto_20180305_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to=employers.models.headshot_location),
        ),
    ]
