# Generated by Django 2.0.2 on 2018-03-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_employee_headshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
    ]
