# Generated by Django 2.0.2 on 2018-03-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0005_auto_20180306_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
