# Generated by Django 2.0.2 on 2018-03-12 15:54

from django.db import migrations, models
import django_otp.util


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='key',
            field=models.CharField(default=b'439f9f02960b5a798f55d4e8fc712f416346c0ab', max_length=40, unique=True, validators=[django_otp.util.hex_validator]),
        ),
    ]
