# Generated by Django 2.0.2 on 2018-03-12 15:55

from django.db import migrations, models
import django_otp.util


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_auto_20180312_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='key',
            field=models.CharField(default=b'd07b543a741df92a93402ad0bfd2853701b7736a', max_length=40, unique=True, validators=[django_otp.util.hex_validator]),
        ),
    ]
