# Generated by Django 2.0.2 on 2018-03-12 15:55

from django.db import migrations, models
import django_otp.util


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0003_auto_20180312_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='key',
            field=models.CharField(default=b'60e0f02014a0d9a3036f9df03aecd98c30d02ff5', max_length=60, unique=True, validators=[django_otp.util.hex_validator]),
        ),
    ]
