# Generated by Django 2.0.2 on 2018-03-12 15:59

from django.db import migrations, models
import django.db.models.deletion
import django_otp.util


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0004_auto_20180312_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totpdevice',
            name='employee',
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='key',
            field=models.CharField(default=b'd1cdf6c2ccd4b8e3ca55e07d95b257cab26f312d', max_length=60, unique=True, validators=[django_otp.util.hex_validator]),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.Employee'),
        ),
    ]
