# Generated by Django 2.0.2 on 2018-03-12 16:08

from django.db import migrations, models
import django_otp.util


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0005_auto_20180312_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='key',
            field=models.CharField(default=b'408a747e83c65d4b1df1ba9070c18471dffcb983', max_length=60, unique=True, validators=[django_otp.util.hex_validator]),
        ),
    ]
