# Generated by Django 2.0.2 on 2018-03-12 17:08

from django.db import migrations, models
import django_otp.util


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0006_auto_20180312_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='key',
            field=models.CharField(default=b'11c2c2eaf173b589f3f9eadcc1c908b9a14b3508', max_length=60, unique=True, validators=[django_otp.util.hex_validator]),
        ),
    ]
