# Generated by Django 2.0.2 on 2018-03-12 17:09

from django.db import migrations, models
import django_otp.util


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0007_auto_20180312_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='key',
            field=models.CharField(default=b'51439580b4f56127a85e6e803b149c571ca9c15e', max_length=60, unique=True, validators=[django_otp.util.hex_validator]),
        ),
    ]
