# Generated by Django 2.0.2 on 2018-03-12 17:09

from django.db import migrations, models
import django_otp.util


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0008_auto_20180312_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='key',
            field=models.CharField(default=b'ecb00f5f4868f086a34c0b575438714e1ee81241', max_length=60, unique=True, validators=[django_otp.util.hex_validator]),
        ),
    ]
