# Generated by Django 2.0.2 on 2018-03-14 14:00

from django.db import migrations, models
import django_otp.util


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0009_auto_20180312_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='key',
            field=models.CharField(default=b'9b14b1c61f227194ffba67f97d73757f7a34423f', max_length=60, unique=True, validators=[django_otp.util.hex_validator]),
        ),
    ]
