# Generated by Django 2.0.2 on 2018-03-12 19:08

from django.db import migrations, models
import django_otp.util


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0009_auto_20180312_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='key',
            field=models.CharField(default=b'61a903fe9ea5069bbe1aec08386ba08d1fde509e', max_length=60, unique=True, validators=[django_otp.util.hex_validator]),
        ),
    ]
