# Generated by Django 2.0.2 on 2018-03-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0010_auto_20180312_1908'),
        ('otp', '0010_auto_20180314_1400'),
    ]

    operations = [
    ]
