# Generated by Django 2.0.2 on 2018-03-14 14:42

from django.db import migrations, models
import django_otp.util
import otp.models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0011_merge_20180314_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='key',
            field=models.CharField(default=otp.models.default_key, max_length=60, unique=True, validators=[django_otp.util.hex_validator]),
        ),
    ]
