# Generated by Django 2.0.2 on 2018-03-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
