# Generated by Django 2.0.2 on 2018-03-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='date',
        ),
    ]
