# Generated by Django 2.0.2 on 2018-03-07 15:08

from django.db import migrations, models
import django.db.models.deletion
import stores.models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_remove_administrator_user_type'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employers.Address'),
        ),
        migrations.AddField(
            model_name='storeuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=stores.models.storeuser_avatar),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
